(function () {
window.WORD_ARENA_CURATED_DECKS = [
{ topic: "ielts", eng: "significant", vie: "đáng kể", pos: "adj", level: "B2", tag: "ielts", example: "The report shows a significant rise in online learning.", note: "IELTS Essentials · B2" },
{ topic: "ielts", eng: "evidence", vie: "bằng chứng", pos: "n", level: "B2", tag: "ielts", example: "Use evidence to support your opinion.", note: "IELTS Essentials · B2" },
{ topic: "ielts", eng: "consequence", vie: "hậu quả", pos: "n", level: "B2", tag: "ielts", example: "Air pollution has serious consequences for public health.", note: "IELTS Essentials · B2" },
{ topic: "ielts", eng: "beneficial", vie: "có lợi", pos: "adj", level: "B2", tag: "ielts", example: "Regular exercise is beneficial for students.", note: "IELTS Essentials · B2" },
{ topic: "ielts", eng: "whereas", vie: "trong khi đó", pos: "conj", level: "B2", tag: "ielts", example: "Cities offer more jobs, whereas rural areas are often quieter.", note: "IELTS Essentials · B2" },
{ topic: "ielts", eng: "evaluate", vie: "đánh giá", pos: "v", level: "B2", tag: "ielts", example: "The essay evaluates the benefits of public transport.", note: "IELTS Essentials · B2" },
{ topic: "ielts", eng: "perspective", vie: "góc nhìn", pos: "n", level: "B2", tag: "ielts", example: "From an economic perspective, tourism creates jobs.", note: "IELTS Essentials · B2" },
{ topic: "ielts", eng: "solution", vie: "giải pháp", pos: "n", level: "B2", tag: "ielts", example: "A long-term solution is needed for traffic congestion.", note: "IELTS Essentials · B2" },
{ topic: "ielts", eng: "impact", vie: "tác động", pos: "n", level: "B2", tag: "ielts", example: "Technology has a strong impact on communication.", note: "IELTS Essentials · B2" },
{ topic: "ielts", eng: "sustainable", vie: "bền vững", pos: "adj", level: "B2", tag: "ielts", example: "Cities should invest in sustainable transport.", note: "IELTS Essentials · B2" },

{ topic: "toeic", eng: "invoice", vie: "hóa đơn", pos: "n", level: "B1", tag: "toeic", example: "Please send the invoice by email.", note: "TOEIC Essentials · B1" },
{ topic: "toeic", eng: "receipt", vie: "biên lai", pos: "n", level: "B1", tag: "toeic", example: "Keep the receipt for your records.", note: "TOEIC Essentials · B1" },
{ topic: "toeic", eng: "client", vie: "khách hàng", pos: "n", level: "B1", tag: "toeic", example: "The client requested a new meeting time.", note: "TOEIC Essentials · B1" },
{ topic: "toeic", eng: "confirm", vie: "xác nhận", pos: "v", level: "B1", tag: "toeic", example: "Please confirm your reservation.", note: "TOEIC Essentials · B1" },
{ topic: "toeic", eng: "reschedule", vie: "đổi lịch", pos: "v", level: "B1", tag: "toeic", example: "We need to reschedule the appointment.", note: "TOEIC Essentials · B1" },
{ topic: "toeic", eng: "available", vie: "có sẵn", pos: "adj", level: "B1", tag: "toeic", example: "A manager is available after lunch.", note: "TOEIC Essentials · B1" },
{ topic: "toeic", eng: "department", vie: "phòng ban", pos: "n", level: "B1", tag: "toeic", example: "Contact the sales department for details.", note: "TOEIC Essentials · B1" },
{ topic: "toeic", eng: "shipment", vie: "lô hàng", pos: "n", level: "B1", tag: "toeic", example: "The shipment will arrive next week.", note: "TOEIC Essentials · B1" },
{ topic: "toeic", eng: "policy", vie: "chính sách", pos: "n", level: "B1", tag: "toeic", example: "Read the refund policy carefully.", note: "TOEIC Essentials · B1" },
{ topic: "toeic", eng: "deadline", vie: "hạn chót", pos: "n", level: "B1", tag: "toeic", example: "The project deadline is Friday.", note: "TOEIC Essentials · B1" },

{ topic: "academic", eng: "research", vie: "nghiên cứu", pos: "n", level: "C1", tag: "academic", example: "The research focuses on language learning.", note: "Academic Vocabulary · C1" },
{ topic: "academic", eng: "methodology", vie: "phương pháp luận", pos: "n", level: "C1", tag: "academic", example: "The paper explains its research methodology.", note: "Academic Vocabulary · C1" },
{ topic: "academic", eng: "hypothesis", vie: "giả thuyết", pos: "n", level: "C1", tag: "academic", example: "The experiment tested a simple hypothesis.", note: "Academic Vocabulary · C1" },
{ topic: "academic", eng: "analysis", vie: "sự phân tích", pos: "n", level: "C1", tag: "academic", example: "The analysis compares two learning methods.", note: "Academic Vocabulary · C1" },
{ topic: "academic", eng: "framework", vie: "khung lý thuyết", pos: "n", level: "C1", tag: "academic", example: "This framework helps explain motivation.", note: "Academic Vocabulary · C1" },
{ topic: "academic", eng: "interpret", vie: "diễn giải", pos: "v", level: "C1", tag: "academic", example: "Students must interpret the results carefully.", note: "Academic Vocabulary · C1" },
{ topic: "academic", eng: "cite", vie: "trích dẫn", pos: "v", level: "C1", tag: "academic", example: "Remember to cite every source you use.", note: "Academic Vocabulary · C1" },
{ topic: "academic", eng: "literature", vie: "tài liệu học thuật", pos: "n", level: "C1", tag: "academic", example: "The literature shows mixed findings.", note: "Academic Vocabulary · C1" },
{ topic: "academic", eng: "variable", vie: "biến số", pos: "n", level: "C1", tag: "academic", example: "Income was an important variable in the study.", note: "Academic Vocabulary · C1" },
{ topic: "academic", eng: "valid", vie: "có giá trị", pos: "adj", level: "C1", tag: "academic", example: "The survey produced valid results.", note: "Academic Vocabulary · C1" },

{ topic: "daily-life", eng: "schedule", vie: "lịch trình", pos: "n", level: "A2", tag: "daily-life", example: "My schedule is full this morning.", note: "Daily English · A2" },
{ topic: "daily-life", eng: "routine", vie: "thói quen hằng ngày", pos: "n", level: "A2", tag: "daily-life", example: "My morning routine starts with breakfast.", note: "Daily English · A2" },
{ topic: "daily-life", eng: "appointment", vie: "cuộc hẹn", pos: "n", level: "A2", tag: "daily-life", example: "I have a dentist appointment at three.", note: "Daily English · A2" },
{ topic: "daily-life", eng: "grocery", vie: "thực phẩm mua ở cửa hàng", pos: "n", level: "A2", tag: "daily-life", example: "We need to buy groceries after work.", note: "Daily English · A2" },
{ topic: "daily-life", eng: "neighbor", vie: "hàng xóm", pos: "n", level: "A2", tag: "daily-life", example: "Our neighbor helped us carry the boxes.", note: "Daily English · A2" },
{ topic: "daily-life", eng: "borrow", vie: "mượn", pos: "v", level: "A2", tag: "daily-life", example: "Can I borrow your charger?", note: "Daily English · A2" },
{ topic: "daily-life", eng: "return", vie: "trả lại", pos: "v", level: "A2", tag: "daily-life", example: "Please return the book tomorrow.", note: "Daily English · A2" },
{ topic: "daily-life", eng: "prepare", vie: "chuẩn bị", pos: "v", level: "A2", tag: "daily-life", example: "I need to prepare dinner.", note: "Daily English · A2" },
{ topic: "daily-life", eng: "comfortable", vie: "thoải mái", pos: "adj", level: "A2", tag: "daily-life", example: "This chair is comfortable.", note: "Daily English · A2" },
{ topic: "daily-life", eng: "probably", vie: "có lẽ", pos: "adv", level: "A2", tag: "daily-life", example: "I will probably stay home tonight.", note: "Daily English · A2" },

{ topic: "university", eng: "lecture", vie: "bài giảng", pos: "n", level: "B1", tag: "university", example: "The lecture starts at nine.", note: "University Survival · B1" },
{ topic: "university", eng: "assignment", vie: "bài tập được giao", pos: "n", level: "B1", tag: "university", example: "The assignment is due tomorrow.", note: "University Survival · B1" },
{ topic: "university", eng: "deadline", vie: "hạn nộp", pos: "n", level: "B1", tag: "university", example: "The deadline for the essay is Monday.", note: "University Survival · B1" },
{ topic: "university", eng: "semester", vie: "học kỳ", pos: "n", level: "B1", tag: "university", example: "This semester has five main courses.", note: "University Survival · B1" },
{ topic: "university", eng: "campus", vie: "khuôn viên trường", pos: "n", level: "B1", tag: "university", example: "The library is near the center of campus.", note: "University Survival · B1" },
{ topic: "university", eng: "major", vie: "ngành học chính", pos: "n", level: "B1", tag: "university", example: "Her major is computer science.", note: "University Survival · B1" },
{ topic: "university", eng: "scholarship", vie: "học bổng", pos: "n", level: "B1", tag: "university", example: "He applied for a scholarship.", note: "University Survival · B1" },
{ topic: "university", eng: "attendance", vie: "sự có mặt", pos: "n", level: "B1", tag: "university", example: "Attendance is required for the lab class.", note: "University Survival · B1" },
{ topic: "university", eng: "submit", vie: "nộp", pos: "v", level: "B1", tag: "university", example: "Submit your report online.", note: "University Survival · B1" },
{ topic: "university", eng: "grade", vie: "điểm số", pos: "n", level: "B1", tag: "university", example: "The final grade includes a presentation.", note: "University Survival · B1" },

{ topic: "travel", eng: "reservation", vie: "đặt chỗ", pos: "n", level: "A2", tag: "travel", example: "I made a hotel reservation for two nights.", note: "Travel English · A2" },
{ topic: "travel", eng: "departure", vie: "khởi hành", pos: "n", level: "A2", tag: "travel", example: "The departure time is seven thirty.", note: "Travel English · A2" },
{ topic: "travel", eng: "destination", vie: "điểm đến", pos: "n", level: "A2", tag: "travel", example: "Da Nang is our next destination.", note: "Travel English · A2" },
{ topic: "travel", eng: "luggage", vie: "hành lý", pos: "n", level: "A2", tag: "travel", example: "Please keep your luggage with you.", note: "Travel English · A2" },
{ topic: "travel", eng: "passport", vie: "hộ chiếu", pos: "n", level: "A2", tag: "travel", example: "You need your passport at the airport.", note: "Travel English · A2" },
{ topic: "travel", eng: "ticket", vie: "vé", pos: "n", level: "A2", tag: "travel", example: "She bought a train ticket online.", note: "Travel English · A2" },
{ topic: "travel", eng: "arrival", vie: "sự đến nơi", pos: "n", level: "A2", tag: "travel", example: "Our arrival time is ten o'clock.", note: "Travel English · A2" },
{ topic: "travel", eng: "guide", vie: "hướng dẫn viên", pos: "n", level: "A2", tag: "travel", example: "The guide explained the history of the old town.", note: "Travel English · A2" },
{ topic: "travel", eng: "delay", vie: "sự chậm trễ", pos: "n", level: "A2", tag: "travel", example: "There was a delay at the airport.", note: "Travel English · A2" },
{ topic: "travel", eng: "boarding pass", vie: "thẻ lên máy bay", pos: "n", level: "A2", tag: "travel", example: "Show your boarding pass at the gate.", note: "Travel English · A2" },

{ topic: "conversation", eng: "actually", vie: "thật ra", pos: "adv", level: "A2", tag: "conversation", example: "Actually, I have already seen that movie.", note: "Common Conversation · A2" },
{ topic: "conversation", eng: "probably", vie: "có lẽ", pos: "adv", level: "A2", tag: "conversation", example: "She will probably join us later.", note: "Common Conversation · A2" },
{ topic: "conversation", eng: "anyway", vie: "dù sao thì", pos: "adv", level: "A2", tag: "conversation", example: "Anyway, let's start the meeting.", note: "Common Conversation · A2" },
{ topic: "conversation", eng: "guess", vie: "đoán", pos: "v", level: "A2", tag: "conversation", example: "I guess we should leave now.", note: "Common Conversation · A2" },
{ topic: "conversation", eng: "prefer", vie: "thích hơn", pos: "v", level: "A2", tag: "conversation", example: "I prefer tea to coffee.", note: "Common Conversation · A2" },
{ topic: "conversation", eng: "agree", vie: "đồng ý", pos: "v", level: "A2", tag: "conversation", example: "I agree with your idea.", note: "Common Conversation · A2" },
{ topic: "conversation", eng: "suggest", vie: "đề xuất", pos: "v", level: "A2", tag: "conversation", example: "Can you suggest a good restaurant?", note: "Common Conversation · A2" },
{ topic: "conversation", eng: "sound", vie: "nghe có vẻ", pos: "v", level: "A2", tag: "conversation", example: "That sounds interesting.", note: "Common Conversation · A2" },
{ topic: "conversation", eng: "matter", vie: "quan trọng", pos: "v", level: "A2", tag: "conversation", example: "It does not matter to me.", note: "Common Conversation · A2" },
{ topic: "conversation", eng: "instead", vie: "thay vào đó", pos: "adv", level: "A2", tag: "conversation", example: "Let's take the bus instead.", note: "Common Conversation · A2" }
];
})();
