(function () {
window.WORD_ARENA_CURATED_DECKS = [
{ topic: "ielts", eng: "significant", vie: "đáng kể", pos: "adj", level: "B2", tag: "IELTS", example: "The study found a significant increase in online learning.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "evidence", vie: "bằng chứng", pos: "n", level: "B2", tag: "IELTS", example: "Writers should support their opinion with clear evidence.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "consequence", vie: "hậu quả", pos: "n", level: "B2", tag: "IELTS", example: "Air pollution can have serious consequences for public health.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "beneficial", vie: "có lợi", pos: "adj", level: "B2", tag: "IELTS", example: "Regular exercise is beneficial for both physical and mental health.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "whereas", vie: "trong khi đó", pos: "conj", level: "B2", tag: "IELTS", example: "Urban areas offer more jobs, whereas rural areas are often quieter.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "evaluate", vie: "đánh giá", pos: "v", level: "B2", tag: "IELTS", example: "The essay evaluates the advantages of public transport.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "perspective", vie: "góc nhìn", pos: "n", level: "B2", tag: "IELTS", example: "From an economic perspective, tourism can create many jobs.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "solution", vie: "giải pháp", pos: "n", level: "B2", tag: "IELTS", example: "A long-term solution is needed to reduce traffic congestion.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "challenge", vie: "thách thức", pos: "n", level: "B2", tag: "IELTS", example: "Climate change is a major challenge for many countries.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "impact", vie: "tác động", pos: "n", level: "B2", tag: "IELTS", example: "Technology has a strong impact on the way people communicate.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "trend", vie: "xu hướng", pos: "n", level: "B2", tag: "IELTS", example: "There is a growing trend toward remote work.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "argument", vie: "lập luận", pos: "n", level: "B2", tag: "IELTS", example: "A strong argument needs examples and evidence.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "contrast", vie: "sự tương phản", pos: "n", level: "B2", tag: "IELTS", example: "The chart shows a clear contrast between the two age groups.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "influence", vie: "ảnh hưởng", pos: "n", level: "B2", tag: "IELTS", example: "Parents can have a powerful influence on children's habits.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "priority", vie: "ưu tiên", pos: "n", level: "B2", tag: "IELTS", example: "Improving public transport should be a priority.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "reliable", vie: "đáng tin cậy", pos: "adj", level: "B2", tag: "IELTS", example: "Students need reliable information for academic writing.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "sustainable", vie: "bền vững", pos: "adj", level: "B2", tag: "IELTS", example: "Cities should invest in sustainable transport systems.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "contribute", vie: "đóng góp", pos: "v", level: "B2", tag: "IELTS", example: "Education can contribute to economic growth.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "complex", vie: "phức tạp", pos: "adj", level: "B2", tag: "IELTS", example: "The relationship between income and happiness is complex.", note: "Curated local IELTS B2 seed" },
{ topic: "ielts", eng: "practical", vie: "thực tế", pos: "adj", level: "B2", tag: "IELTS", example: "The proposal offers a practical way to save energy.", note: "Curated local IELTS B2 seed" },

{ topic: "travel", eng: "reservation", vie: "đặt chỗ", pos: "n", level: "A2", tag: "travel", example: "I made a hotel reservation for two nights.", note: "Curated local Travel A2 seed" },
{ topic: "travel", eng: "departure", vie: "khởi hành", pos: "n", level: "A2", tag: "travel", example: "The departure time is seven thirty.", note: "Curated local Travel A2 seed" },
{ topic: "travel", eng: "destination", vie: "điểm đến", pos: "n", level: "A2", tag: "travel", example: "Da Nang is our next destination.", note: "Curated local Travel A2 seed" },
{ topic: "travel", eng: "luggage", vie: "hành lý", pos: "n", level: "A2", tag: "travel", example: "Please keep your luggage with you.", note: "Curated local Travel A2 seed" },
{ topic: "travel", eng: "suitcase", vie: "chiếc va li", pos: "n", level: "A2", tag: "travel", example: "My suitcase is too heavy for the bus.", note: "Curated local Travel A2 seed" },
{ topic: "travel", eng: "souvenir", vie: "quà lưu niệm", pos: "n", level: "A2", tag: "travel", example: "I bought a small souvenir at the market.", note: "Curated local Travel A2 seed" },
{ topic: "travel", eng: "passport", vie: "hộ chiếu", pos: "n", level: "A2", tag: "travel", example: "You need your passport at the airport.", note: "Curated local Travel A2 seed" },
{ topic: "travel", eng: "ticket", vie: "vé", pos: "n", level: "A2", tag: "travel", example: "She bought a train ticket online.", note: "Curated local Travel A2 seed" },
{ topic: "travel", eng: "arrival", vie: "sự đến nơi", pos: "n", level: "A2", tag: "travel", example: "Our arrival time is ten o'clock.", note: "Curated local Travel A2 seed" },
{ topic: "travel", eng: "guide", vie: "hướng dẫn viên", pos: "n", level: "A2", tag: "travel", example: "The guide explained the history of the old town.", note: "Curated local Travel A2 seed" },

{ topic: "technology", eng: "algorithm", vie: "thuật toán", pos: "n", level: "B1", tag: "technology", example: "The algorithm sorts the list by date.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "database", vie: "cơ sở dữ liệu", pos: "n", level: "B1", tag: "technology", example: "The database stores user profiles.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "deploy", vie: "triển khai", pos: "v", level: "B1", tag: "technology", example: "The team will deploy the app tonight.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "debug", vie: "gỡ lỗi", pos: "v", level: "B1", tag: "technology", example: "She needs to debug the login problem.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "interface", vie: "giao diện", pos: "n", level: "B1", tag: "technology", example: "The interface is simple and easy to use.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "repository", vie: "kho mã nguồn", pos: "n", level: "B1", tag: "technology", example: "Push the latest code to the repository.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "server", vie: "máy chủ", pos: "n", level: "B1", tag: "technology", example: "The server handles many requests every minute.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "request", vie: "yêu cầu", pos: "n", level: "B1", tag: "technology", example: "The browser sends a request to the server.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "response", vie: "phản hồi", pos: "n", level: "B1", tag: "technology", example: "The API response includes a list of words.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "backup", vie: "bản sao lưu", pos: "n", level: "B1", tag: "technology", example: "Create a backup before changing the system.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "feature", vie: "tính năng", pos: "n", level: "B1", tag: "technology", example: "The new feature helps users review words.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "version", vie: "phiên bản", pos: "n", level: "B1", tag: "technology", example: "Install the latest version of the tool.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "configure", vie: "cấu hình", pos: "v", level: "B1", tag: "technology", example: "You must configure the app before deployment.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "integrate", vie: "tích hợp", pos: "v", level: "B1", tag: "technology", example: "The service can integrate with cloud storage.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "authentication", vie: "xác thực", pos: "n", level: "B1", tag: "technology", example: "Authentication protects user accounts.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "authorization", vie: "phân quyền", pos: "n", level: "B1", tag: "technology", example: "Authorization controls what a user can access.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "endpoint", vie: "điểm cuối API", pos: "n", level: "B1", tag: "technology", example: "The endpoint returns vocabulary data.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "validation", vie: "kiểm tra hợp lệ", pos: "n", level: "B1", tag: "technology", example: "Validation prevents empty form submissions.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "cache", vie: "bộ nhớ đệm", pos: "n", level: "B1", tag: "technology", example: "The cache makes the page load faster.", note: "Curated local Technology B1 seed" },
{ topic: "technology", eng: "sync", vie: "đồng bộ", pos: "v", level: "B1", tag: "technology", example: "The app can sync data across devices.", note: "Curated local Technology B1 seed" },

{ topic: "school", eng: "assignment", vie: "bài tập được giao", pos: "n", level: "A2", tag: "school", example: "The assignment is due tomorrow.", note: "Curated local School seed" },
{ topic: "school", eng: "attendance", vie: "sự có mặt", pos: "n", level: "A2", tag: "school", example: "Attendance is important in class.", note: "Curated local School seed" },
{ topic: "business", eng: "negotiate", vie: "đàm phán", pos: "v", level: "B2", tag: "business", example: "The two companies will negotiate a new contract.", note: "Curated local Business seed" },
{ topic: "business", eng: "strategy", vie: "chiến lược", pos: "n", level: "B2", tag: "business", example: "A clear strategy helps the team choose priorities.", note: "Curated local Business seed" },
{ topic: "health", eng: "nutrition", vie: "dinh dưỡng", pos: "n", level: "B1", tag: "health", example: "Good nutrition supports long-term health.", note: "Curated local Health seed" },
{ topic: "health", eng: "recovery", vie: "sự hồi phục", pos: "n", level: "B1", tag: "health", example: "Sleep is important for recovery.", note: "Curated local Health seed" },
{ topic: "environment", eng: "pollution", vie: "ô nhiễm", pos: "n", level: "B1", tag: "environment", example: "Air pollution affects many large cities.", note: "Curated local Environment seed" },
{ topic: "environment", eng: "renewable", vie: "có thể tái tạo", pos: "adj", level: "B2", tag: "environment", example: "Solar power is a renewable energy source.", note: "Curated local Environment seed" },
{ topic: "daily-life", eng: "routine", vie: "thói quen hằng ngày", pos: "n", level: "A2", tag: "daily-life", example: "My morning routine starts with breakfast.", note: "Curated local Daily Life seed" },
{ topic: "daily-life", eng: "errand", vie: "việc vặt", pos: "n", level: "B1", tag: "daily-life", example: "I need to run an errand after work.", note: "Curated local Daily Life seed" },
{ topic: "academic", eng: "methodology", vie: "phương pháp luận", pos: "n", level: "C1", tag: "academic", example: "The paper explains its research methodology.", note: "Curated local Academic English seed" },
{ topic: "academic", eng: "hypothesis", vie: "giả thuyết", pos: "n", level: "C1", tag: "academic", example: "The experiment tested a simple hypothesis.", note: "Curated local Academic English seed" },
{ topic: "work", eng: "deadline", vie: "hạn chót", pos: "n", level: "A2", tag: "work", example: "The project deadline is Friday.", note: "Curated local Work seed" },
{ topic: "work", eng: "collaborate", vie: "hợp tác", pos: "v", level: "B1", tag: "work", example: "Designers and developers collaborate on the product.", note: "Curated local Work seed" }
];
})();
